anypoint_mode_2:
  alpha: 30
  beta: 4
  crop_bottom: 0.7
  crop_top: 0.098
  zoom: 1
driver:
  alpha: -63
  beta: -25
  roll: -124
  zoom: 0.8
left_window:
  alpha: 0
  beta: -88
  roll: -11
  zoom: 4.900000000000001
original:
  rotate: 5
panorama:
  alpha: 144.5
  alpha_from: 0.0
  alpha_max: 106
  beta: -9.5
  crop_bottom: 0.972
  crop_left: 0.259
  crop_right: 0.826
  crop_top: 0.237
right_window:
  alpha: 53
  beta: 77
  roll: 5
  zoom: 0.9
second_driver:
  alpha: -66
  beta: 38
  roll: 125
  zoom: 4.4
x_panorama:
  alpha_max: 110
  alpha_min: 33
  crop_bottom: 0.721
  crop_top: 0.52
