from PyQt6 import QtWidgets, QtCore


class ZoomButton(object):
    def __init__(self, controller):
        self.controller = controller
        self.add_zoom_button_anypoint1()
        self.add_zoom_button_feature_point()
        self.add_zoom_button_feature_matching()
        self.add_zoom_button_optical_flow()
        self.add_zoom_button_disparity()
        self.add_word_in_button()

    def add_zoom_button_anypoint1(self):
        self.frame_image_stereo = QtWidgets.QFrame(parent=self.controller.ui.frame_image_output)
        self.frame_image_stereo.setGeometry(QtCore.QRect(4, 4, 60, 30))
        self.frame_image_stereo.setMinimumSize(QtCore.QSize(60, 30))
        self.frame_image_stereo.setMaximumSize(QtCore.QSize(60, 30))
        self.frame_image_stereo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_image_stereo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_image_stereo.setObjectName("frame_image_stereo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_image_stereo)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_zoom_in_stereo = QtWidgets.QPushButton(parent=self.frame_image_stereo)
        self.btn_zoom_in_stereo.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_stereo.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_stereo.setObjectName("btn_zoom_in_stereo")
        self.horizontalLayout.addWidget(self.btn_zoom_in_stereo)
        self.btn_zoom_out_stereo = QtWidgets.QPushButton(parent=self.frame_image_stereo)
        self.btn_zoom_out_stereo.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_stereo.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_stereo.setObjectName("btn_zoom_out_stereo")
        self.horizontalLayout.addWidget(self.btn_zoom_out_stereo)

    def add_zoom_button_feature_point(self):
        self.frame_zoom_feature_point = QtWidgets.QFrame(parent=self.controller.ui.frame_feature_point)
        self.frame_zoom_feature_point.setGeometry(QtCore.QRect(4, 4, 60, 30))
        self.frame_zoom_feature_point.setMinimumSize(QtCore.QSize(60, 30))
        self.frame_zoom_feature_point.setMaximumSize(QtCore.QSize(60, 30))
        self.frame_zoom_feature_point.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_zoom_feature_point.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_zoom_feature_point.setObjectName("frame_zoom_feature_point")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_zoom_feature_point)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_zoom_in_feature_point = QtWidgets.QPushButton(parent=self.frame_zoom_feature_point)
        self.btn_zoom_in_feature_point.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_feature_point.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_feature_point.setObjectName("btn_zoom_out_feature_point")
        self.horizontalLayout_5.addWidget(self.btn_zoom_in_feature_point)
        self.btn_zoom_out_feature_point = QtWidgets.QPushButton(parent=self.frame_zoom_feature_point)
        self.btn_zoom_out_feature_point.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_feature_point.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_feature_point.setObjectName("btn_zoom_out_feature_point")
        self.horizontalLayout_5.addWidget(self.btn_zoom_out_feature_point)

    def add_zoom_button_feature_matching(self):
        self.frame_zoom_feature_mathing = QtWidgets.QFrame(parent=self.controller.ui.frame_feature_matching)
        self.frame_zoom_feature_mathing.setGeometry(QtCore.QRect(4, 4, 60, 30))
        self.frame_zoom_feature_mathing.setMinimumSize(QtCore.QSize(60, 30))
        self.frame_zoom_feature_mathing.setMaximumSize(QtCore.QSize(60, 30))
        self.frame_zoom_feature_mathing.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_zoom_feature_mathing.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_zoom_feature_mathing.setObjectName("frame_zoom_feature_mathing")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_zoom_feature_mathing)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_zoom_in_feature_matching = QtWidgets.QPushButton(parent=self.frame_zoom_feature_mathing)
        self.btn_zoom_in_feature_matching.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_feature_matching.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_feature_matching.setObjectName("btn_zoom_in_feature_matching")
        self.horizontalLayout_4.addWidget(self.btn_zoom_in_feature_matching)
        self.btn_zoom_out_feature_matching = QtWidgets.QPushButton(parent=self.frame_zoom_feature_mathing)
        self.btn_zoom_out_feature_matching.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_feature_matching.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_feature_matching.setObjectName("btn_zoom_out_feature_matching")
        self.horizontalLayout_4.addWidget(self.btn_zoom_out_feature_matching)

    def add_zoom_button_disparity(self):
        self.frame_zoom_disparity = QtWidgets.QFrame(parent=self.controller.ui.frame_disparity_image)
        self.frame_zoom_disparity.setGeometry(QtCore.QRect(4, 4, 60, 30))
        self.frame_zoom_disparity.setMinimumSize(QtCore.QSize(60, 30))
        self.frame_zoom_disparity.setMaximumSize(QtCore.QSize(60, 30))
        self.frame_zoom_disparity.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_zoom_disparity.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_zoom_disparity.setObjectName("frame_zoom_disparity")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_zoom_disparity)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_zoom_in_disparity = QtWidgets.QPushButton(parent=self.frame_zoom_disparity)
        self.btn_zoom_in_disparity.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_disparity.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_disparity.setObjectName("btn_zoom_in_disparity")
        self.horizontalLayout_2.addWidget(self.btn_zoom_in_disparity)
        self.btn_zoom_out_disparity = QtWidgets.QPushButton(parent=self.frame_zoom_disparity)
        self.btn_zoom_out_disparity.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_disparity.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_disparity.setObjectName("btn_zoom_out_disparity")
        self.horizontalLayout_2.addWidget(self.btn_zoom_out_disparity)

    def add_zoom_button_optical_flow(self):
        self.frame_zoom_optical_flow = QtWidgets.QFrame(parent=self.controller.ui.frame_optical_flow)
        self.frame_zoom_optical_flow.setGeometry(QtCore.QRect(4, 4, 60, 30))
        self.frame_zoom_optical_flow.setMinimumSize(QtCore.QSize(60, 30))
        self.frame_zoom_optical_flow.setMaximumSize(QtCore.QSize(60, 30))
        self.frame_zoom_optical_flow.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_zoom_optical_flow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_zoom_optical_flow.setObjectName("frame_zoom_optical_flow")
        self.horizontalLayout_optical_flow = QtWidgets.QHBoxLayout(self.frame_zoom_optical_flow)
        self.horizontalLayout_optical_flow.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_optical_flow.setSpacing(2)
        self.horizontalLayout_optical_flow.setObjectName("horizontalLayout_optical_flow")
        self.btn_zoom_in_optical_flow = QtWidgets.QPushButton(parent=self.frame_zoom_optical_flow)
        self.btn_zoom_in_optical_flow.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_optical_flow.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_in_optical_flow.setObjectName("btn_zoom_in_optical_flow")
        self.horizontalLayout_optical_flow.addWidget(self.btn_zoom_in_optical_flow)
        self.btn_zoom_out_optical_flow = QtWidgets.QPushButton(parent=self.frame_zoom_optical_flow)
        self.btn_zoom_out_optical_flow.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_optical_flow.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_zoom_out_optical_flow.setObjectName("btn_zoom_out_optical_flow")
        self.horizontalLayout_optical_flow.addWidget(self.btn_zoom_out_optical_flow)

    def add_word_in_button(self):
        _translate = QtCore.QCoreApplication.translate
        self.btn_zoom_in_stereo.setText(_translate("MainWindow", "+"))
        self.btn_zoom_out_stereo.setText(_translate("MainWindow", "-"))
        self.btn_zoom_in_feature_point.setText(_translate("MainWindow", "+"))
        self.btn_zoom_out_feature_point.setText(_translate("MainWindow", "-"))
        self.btn_zoom_in_feature_matching.setText(_translate("MainWindow", "+"))
        self.btn_zoom_out_feature_matching.setText(_translate("MainWindow", "-"))
        self.btn_zoom_in_optical_flow.setText(_translate("MainWindow", "+"))
        self.btn_zoom_out_optical_flow.setText(_translate("MainWindow", "-"))
        self.btn_zoom_in_disparity.setText(_translate("MainWindow", "+"))
        self.btn_zoom_out_disparity.setText(_translate("MainWindow", "-"))